export {
  setCache,
  getCache,
  deleteCache,
  cleanExpiredCache,
  getCacheStats,
  hasCache,
  getStoreNames,
  deleteDatabase,
  getAllDatabaseNames,
  getStorageQuota,
  checkStorageQuota,
  getAllDatabasesUsage,
  DEFAULT_DB_NAME,
  DEFAULT_STORE_NAME_GENERAL,
  DEFAULT_CACHE_EXPIRE_HOURS,
  loadImageWithCache,
  loadImageProgressiveWithCache,
} from '../../lib/imageCache.js';
